# Generated by Django 4.1.5 on 2023-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(help_text='Descripcion corta del producto', max_length=5000, null=True),
        ),
    ]
