# Generated by Django 4.1.5 on 2023-01-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('USED', 'Usado'), ('REFURBISHED', 'Remanufacturado')], default='NEW', help_text='Condicion del producto', max_length=255),
        ),
    ]
