# Generated by Django 4.1 on 2022-08-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_store_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='child',
        ),
    ]
