# Generated by Django 4.1.5 on 2023-01-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_products_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('SERVICE', 'SERVICIOS'), ('MERCHANDISE', 'MERCANCIA')], default='SERVICE', help_text='determina si un bien es un producto o un servicio, solo los servicios pueden llevar price=null', max_length=200),
        ),
    ]
