# Generated by Django 4.1.5 on 2023-01-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_products_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(help_text='sufijo unico para encontrar el producto por la URL', max_length=800, null=True, unique=True),
        ),
    ]
