# Generated by Django 4.1.5 on 2023-01-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity_name',
            field=models.CharField(choices=[('order', 'Orden'), ('message', 'Mensaje'), ('product_order', 'Orden de Producto')], max_length=255),
        ),
    ]
