# Generated by Django 4.1.5 on 2023-01-23 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notification_entity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='prueba', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='channel_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.channelgroup'),
        ),
    ]
