# Generated by Django 4.1 on 2022-08-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(help_text='si es null se marcara como gratuito', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('SERVICE', 'SERVICIOS'), ('MERCHANDISE', 'MERCANCIA')], default='SERVICE', help_text='determina si un bien es un producto o un servicio, solo los servicios pueden llevar price=null', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(help_text='Marca del producto, si es null se entendera como generica', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.brand'),
        ),
        migrations.AlterField(
            model_name='products',
            name='store',
            field=models.ForeignKey(help_text='Tienda que publico el producto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.store'),
        ),
    ]
