# Generated by Django 4.1 on 2022-08-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_products_discount_products_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('USED', 'Usado'), ('REFURBISHED', 'Remanufacturado')], default='NEW', max_length=50),
        ),
    ]
