# Generated by Django 4.1.5 on 2023-01-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notification_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='money',
            field=models.FloatField(default=0, help_text='Dinero por retirar de la tienda'),
        ),
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.FloatField(default=0, help_text='Creditos para retirar premios usuario'),
        ),
    ]
