# Generated by Django 4.1.5 on 2023-01-24 23:26

from django.db import migrations
from core.choices.model_choices import RoleChoices
from django.contrib.auth.hashers import make_password
from django.utils.text import slugify
def create_main_store_and_user(apps, schema_editor):

    User = apps.get_model("core","User")
    Store = apps.get_model("core","Store")
    store = Store(name="MLS parts, C.A", bussiness_legal_id="294954480")
    store.slug = f"{slugify(store.name)}"
    store.save()
    
    User.objects.create(
        first_name="Jorge",
        last_name="Martin Ramos", 
        role=RoleChoices.WEBSITE_OWNER, 
        store=store,
        email="contacto@mlsparts.shop",
        password=make_password("admin"),
        is_active=True,
        is_staff=True,
        is_superuser=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_store_money_user_credits'),
    ]

    operations = [
        migrations.RunPython(create_main_store_and_user)
    ]
