# Generated by Django 4.1.1 on 2022-10-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(help_text='Marca del producto, si es null se entendera como generica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.brand'),
        ),
    ]
