# Generated by Django 4.1.5 on 2023-01-29 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, help_text='Para indicar si el freelance completo la asistencia')),
                ('cart_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cartitem')),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productorder')),
            ],
        ),
    ]
