# Generated by Django 4.1.5 on 2023-01-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_assistance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='assistance',
            name='product_order',
        ),
        migrations.AddField(
            model_name='assistance',
            name='cart_items',
            field=models.ManyToManyField(to='core.cartitem'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='product_orders',
            field=models.ManyToManyField(to='core.productorder'),
        ),
    ]
