# Generated by Django 4.1.2 on 2022-10-15 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_products_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(help_text='Color principal con el que se caracteriza la tienda', max_length=100, null=True)),
                ('secondary_color', models.CharField(help_text='Color secundario con el que se caracteriza la tienda', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.config'),
        ),
    ]
