# Generated by Django 4.1.2 on 2022-10-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_config_store_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
