# Generated by Django 4.1.5 on 2023-01-31 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assistance_customer_alter_assistance_freelance'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='assistance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assistance'),
        ),
    ]
