# Generated by Django 4.1.5 on 2023-02-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_message_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='feedback',
            field=models.BooleanField(null=True),
        ),
    ]
