# Generated by Django 4.1.5 on 2023-02-02 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assistance_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='cart_items',
        ),
        migrations.RemoveField(
            model_name='assistance',
            name='product_orders',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='assistance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assistance'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='assistance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assistance'),
        ),
    ]
