# Generated by Django 4.1.6 on 2023-02-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_giftcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
