# Generated by Django 4.1.6 on 2023-02-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userpayment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
