# Generated by Django 4.1.2 on 2022-10-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cart_purchase_remove_productorder_costumer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productorder',
            constraint=models.UniqueConstraint(models.F('cart'), models.F('product'), name='unique_cart_product_order', violation_error_message='No pueden haber mas de 2 ordenes de producto por carrito'),
        ),
    ]
