# Generated by Django 4.1.3 on 2022-11-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_productorder_unique_cart_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='Nombre o título del producto', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(help_text='sufijo unico para encontrar el producto por la URL', null=True, unique=True),
        ),
    ]
