# Generated by Django 4.1.6 on 2023-02-09 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_passwordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('d6bdad1a-fcec-4137-9e04-cacf43e02db6')),
        ),
    ]
