# Generated by Django 4.1.6 on 2023-02-09 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_passwordtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('b67a20df-0af6-4caa-a5a9-7cdf3b80394d')),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('paypal', 'Paypal'), ('coinbase', 'Coinbase crypto'), ('pago_movil', 'Pago Movil'), ('free_item', 'Productos Gratuitos'), ('transferencia_nacional', 'Transferencia de bancos Nacionales')], max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('email_adress', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('national_bank', models.CharField(choices=[('0102', 'Banco de Venezuela (BDV)'), ('0104', 'Banco Venezolano de Crédito (BVC)'), ('0105', 'Banco Mercantil'), ('0108', 'Banco Provincial (BBVA)'), ('0114', 'Bancaribe'), ('0115', 'Banco Exterior'), ('0128', 'Banco Caroní'), ('0134', 'Banesco Banco Universal'), ('0137', 'Sofitasa'), ('0138', 'Banco Plaza'), ('0146', 'Bangente'), ('0151', 'Banco Fondo Común (BFC)'), ('0156', '100% Banco'), ('0157', 'Del Sur Banco Universal'), ('0163', 'Banco del Tesoro'), ('0166', 'Banco Agrícola de Venezuela'), ('0168', 'Bancrecer'), ('0169', 'Mi Banco, Banco Microfinanciero C.A'), ('0171', 'Banco Activo'), ('0172', 'Bancamiga'), ('0174', 'Banplus'), ('0175', 'Banco Bicentenario del Pueblo'), ('0177', 'Banco de la Fuerza Armada Nacional Bolivariana (BANFANB)'), ('0191', 'Banco Nacional de Crédito (BNC)')], max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
