# Generated by Django 4.1.3 on 2022-11-14 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_products_large_description_alter_products_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='last_name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='receipt',
            field=models.FileField(help_text='Campo para hacer referencia a la ubicacion relativa del archivo del recibo de compra', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la marca'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Nombre de la marca', max_length=255),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion de datos'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sub_total',
            field=models.FloatField(default=0, help_text='Subtotal de los productos del carrito'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0, help_text='Total del producto del carrito'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(help_text='Usuario a quien pertenece el carrito', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nombre de la categoria', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion del la categoria'),
        ),
        migrations.AlterField(
            model_name='config',
            name='whatsapp_number',
            field=models.CharField(help_text='Numero que aparecera en el icono de whatsapp de la tienda', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='document_number',
            field=models.CharField(help_text='Numero de identificacion del documento', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='document_type',
            field=models.CharField(choices=[('CEDULA', 'Cédula de identidad'), ('LICENCIA_CONDUCIR', 'Licencia de Conducir'), ('PASAPORTE', 'Pasaporte'), ('RIF', 'Registro de Información Fiscal')], help_text='Tipo de documento, si es RIF o cedula', max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='person_type',
            field=models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Juridica, Empresa'), ('G', 'Ente Gubernamental'), ('E', 'Persona Extranjera Legal')], help_text='Tipo de persona para saber si es una empresa o una persona natural', max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(help_text='Usuario al que pertenece la informacion', on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de subida del documento'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(help_text='Ruta relativa del archivo', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(help_text='Nombre del archivo', max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de la Compra'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion de la compra'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(help_text='Cuerpo del review', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion del review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(help_text='Producto al que pertenece el review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.products'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0, help_text='Puntuacion dada por el usuario a la calidad del producto'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(help_text='Titulo del review', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha en que se actualiza el review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realizo el review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(help_text='Categoria principal a la que se dedica la empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='config',
            field=models.OneToOneField(help_text='relacion con confoguracion de la Empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.config'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de ingreso al sistema'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(help_text='Una breve descripcion de la Empresa', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(help_text='imagen que contiene el logotipo de la empresa', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Nombre de la tienda', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='parent',
            field=models.ForeignKey(help_text='Referencia a una tienda padre que la haya referenciado o en caso de ser franquicia, la empresa matriz', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_store', to='core.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(help_text='sufijo para ubicar la tienda facilmente por URL', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de actualizacion de la informacion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='Breve descripcion acerca del usuario', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='born_date',
            field=models.DateField(help_text='Fecha de nacimiento del usuario', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='fecha de ingreso al sistema'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Correo electronico del usuario', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Nombres del Usuario', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Booleano para saber si la cuenta esta activada y operativa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Booleano para saber si pertenece a los administradores'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Apellidos del Usuario', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BASE_USER', 'Usuario Sin rol')], default='BASE_USER', help_text='Literal para identificar uso de roles', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(help_text='tienda a la que pertenece, puede ser nulo en caso de ser cliente o freelance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='product',
            field=models.ForeignKey(help_text='Producto agregado a la lista de deseos', on_delete=django.db.models.deletion.CASCADE, to='core.products'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(help_text='Usuario que agrego este producto a su lista', on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
