# Generated by Django 4.1.6 on 2023-02-09 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_passwordtoken_token_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='payment_methods',
            field=models.ManyToManyField(to='core.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c7f46a44-c250-4386-8cab-a83a353fabfa')),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
