# Generated by Django 4.1.6 on 2023-02-09 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_paymentmethod_user_user_payment_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c3695b98-69d5-4c0d-b7dd-0b08a9219741')),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='national_bank',
            field=models.CharField(blank=True, choices=[('0102', 'Banco de Venezuela (BDV)'), ('0104', 'Banco Venezolano de Crédito (BVC)'), ('0105', 'Banco Mercantil'), ('0108', 'Banco Provincial (BBVA)'), ('0114', 'Bancaribe'), ('0115', 'Banco Exterior'), ('0128', 'Banco Caroní'), ('0134', 'Banesco Banco Universal'), ('0137', 'Sofitasa'), ('0138', 'Banco Plaza'), ('0146', 'Bangente'), ('0151', 'Banco Fondo Común (BFC)'), ('0156', '100% Banco'), ('0157', 'Del Sur Banco Universal'), ('0163', 'Banco del Tesoro'), ('0166', 'Banco Agrícola de Venezuela'), ('0168', 'Bancrecer'), ('0169', 'Mi Banco, Banco Microfinanciero C.A'), ('0171', 'Banco Activo'), ('0172', 'Bancamiga'), ('0174', 'Banplus'), ('0175', 'Banco Bicentenario del Pueblo'), ('0177', 'Banco de la Fuerza Armada Nacional Bolivariana (BANFANB)'), ('0191', 'Banco Nacional de Crédito (BNC)')], max_length=255, null=True),
        ),
    ]
