# Generated by Django 4.1.6 on 2023-02-09 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_passwordtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('5965f8f0-f8d3-4b95-bc74-d38eb39dda8d')),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
