# Generated by Django 4.1.3 on 2022-12-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_cart_id_alter_cartitem_cart_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('coinbase', 'Coinbase crypto'), ('pago_movil', 'Pago Movil')], help_text='metodo elegido para el pago', max_length=255),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(help_text='Orden principal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='core.order'),
        ),
    ]
