# Generated by Django 4.1.3 on 2022-12-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_order_payment_method_alter_productorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0, help_text='monto total de la orden de compra'),
        ),
    ]
