# Generated by Django 4.1.6 on 2023-02-11 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_passwordtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('b3d71206-f5c3-4aef-8071-1ff956285901')),
        ),
    ]
