# Generated by Django 4.1.3 on 2022-12-20 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_order_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_coordinates', models.CharField(help_text='Coordenadas de Google Maps', max_length=255)),
                ('is_main', models.BooleanField(default=False, help_text='Indica si la direccion es principal o no')),
                ('state', models.CharField(help_text='Estado o Region de la direccion', max_length=255)),
                ('city', models.CharField(help_text='ciudad de la direccion', max_length=255)),
                ('location', models.CharField(help_text='Localidad, calle o Avenida de la direccion', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='campo para saber la creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='campo para saber cuando se actualizo la direccion')),
                ('user', models.ForeignKey(help_text='Usuario que registro esta direccion', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('user',), name='unique_main_address_user'),
        ),
    ]
