# Generated by Django 4.1.6 on 2023-02-11 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_passwordtoken_token_productstorage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='Localidad, calle o Avenida de la direccion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('2df852ed-2f76-4b48-9d3b-bb1910bd5e94')),
        ),
    ]
