# Generated by Django 4.1.4 on 2022-12-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_address_address_unique_main_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='google_coordinates',
            field=models.CharField(help_text='Coordenadas de Google Maps', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=True, help_text='Indica si la direccion es principal o no'),
        ),
    ]
