# Generated by Django 4.1.6 on 2023-02-12 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_address_city_alter_passwordtoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstorage',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='productstorage',
            name='coordinate_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productstorage',
            name='coordinate_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productstorage',
            name='storage_type',
            field=models.CharField(choices=[('tienda_fisica', 'Tienda Física de la tienda'), ('almacen', 'Almacen de la tienda')], default='tienda_fisica', max_length=255),
        ),
        migrations.AddField(
            model_name='productstorage',
            name='zoom',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('96db1abd-6772-46e2-8b74-806be1cfada5')),
        ),
    ]
