# Generated by Django 4.1.4 on 2022-12-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_address_google_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(help_text='Estado o Region de la direccion', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='subregion',
            field=models.CharField(help_text='ciudad de la direccion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Localidad, calle o Avenida de la direccion', max_length=255, null=True),
        ),
    ]
