# Generated by Django 4.1.6 on 2023-02-14 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_productstorage_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('8dcee748-a1a6-4328-88ed-e8a0942a312d')),
        ),
    ]
