# Generated by Django 4.1.6 on 2023-02-14 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_exportfile_alter_passwordtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportfile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('b3fed30c-ce3f-4899-968a-906c50e2ae48')),
        ),
    ]
