# Generated by Django 4.1.6 on 2023-02-14 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_exportfile_user_alter_passwordtoken_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportfile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('46fe260e-2de3-4fd1-beb8-9a5b2e90c5a9')),
        ),
    ]
