# Generated by Django 4.1.4 on 2022-12-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('coinbase', 'Coinbase crypto'), ('pago_movil', 'Pago Movil'), ('free_item', 'Productos Gratuitos')], help_text='metodo elegido para el pago', max_length=255),
        ),
    ]
