# Generated by Django 4.1.4 on 2022-12-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Delivery o Envio'), ('personally', 'Retiro Personalmente')], default='personally', help_text='Campo para saber como el cliente va a retirar la mercancia', max_length=100),
        ),
    ]
