# Generated by Django 4.1.4 on 2022-12-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Esperando por pago del cliente'), ('VALIDATING_PAYMENT', 'validando pago'), ('PAYMENT_FAILED', 'Pago Fallido'), ('PAYMENT_EXPIRED', 'Pago Expirado'), ('PAYMENT_SUCCESS', 'Pago Exitoso')], default='AWAITING_PAYMENT', help_text='Campo para saber el status de la Transaccion', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
