# Generated by Django 4.1.4 on 2023-01-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_order_paid_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(help_text='categoria padre de esta categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
