# Generated by Django 4.1.5 on 2023-01-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(help_text='imagen que contiene el logotipo de la empresa', null=True, upload_to='uploads/'),
        ),
    ]
