# Generated by Django 4.1.5 on 2023-01-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bussiness_legal_id',
            field=models.CharField(help_text='Numero de Identificacion Comercial de la empresa, varia dependiendo del pais, EJ: Venezuela, RIF.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='company_anual_income',
            field=models.FloatField(help_text='Ingreso Anual de la empresa Expresado en Dolares, Campo no Obligatorio', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='company_employee_number',
            field=models.CharField(choices=[('1-10', 'De uno a Diez'), ('10-50', 'De Diez a Cincuenta'), ('50-250', 'De Cincuenta a Doscientos Cincuenta'), ('>=250', 'Mas de Doscientos Cincuenta')], default='1-10', help_text='Numero estimado de empleados de la Empresa.', max_length=255),
            preserve_default=False,
        ),
    ]
