# Generated by Django 4.1.5 on 2023-01-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_store_bussiness_legal_id_store_company_anual_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('base_user', 'Usuario Sin rol'), ('store_owner', 'Dueño de Tienda'), ('store_operator', 'Operador de tienda'), ('freelance', 'Freelance'), ('customer', 'Cliente'), ('base_user', 'Usuario sin rol')], default='base_user', help_text='Literal para identificar uso de roles', max_length=255),
        ),
    ]
