# Generated by Django 4.1.5 on 2023-01-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_brand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
