# Generated by Django 4.1.5 on 2023-01-15 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ForeignKey(help_text='Miniatura del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_products', to='core.media'),
        ),
    ]
