# Generated by Django 4.1.5 on 2023-01-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_products_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text='campo para ordernar los archivos de acuerdo a una prioridad'),
        ),
    ]
