# Generated by Django 4.1.5 on 2023-01-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_media_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['priority']},
        ),
    ]
