# Generated by Django 4.1.5 on 2023-01-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_media_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at']},
        ),
    ]
