# Generated by Django 4.1.5 on 2023-01-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_order_aditional_info_alter_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
