# Generated by Django 4.1.5 on 2023-01-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_address_short_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0424-436-3570', help_text='Numero de telefono del usuario', max_length=255),
            preserve_default=False,
        ),
    ]
