# Generated by Django 4.1.5 on 2023-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_phone',
            field=models.CharField(default='04244363570', help_text='Telefono Alternativo de Contacto', max_length=255),
            preserve_default=False,
        ),
    ]
