# Generated by Django 4.1.5 on 2023-01-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_address_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('coinbase', 'Coinbase crypto'), ('pago_movil', 'Pago Movil'), ('free_item', 'Productos Gratuitos'), ('transferencia_nacional', 'Transferencia de bancos Nacionales')], help_text='metodo elegido para el pago', max_length=255),
        ),
    ]
