# Generated by Django 4.1.5 on 2023-01-18 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('payment_type', models.CharField(choices=[('paypal', 'Paypal'), ('coinbase', 'Coinbase crypto'), ('pago_movil', 'Pago Movil'), ('free_item', 'Productos Gratuitos'), ('transferencia_nacional', 'Transferencia de bancos Nacionales')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
