# Generated by Django 4.1.5 on 2023-01-18 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_externalpayment_national_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_payments', to='core.order'),
        ),
    ]
