# Generated by Django 4.1.5 on 2023-01-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_externalpayment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpayment',
            name='state',
            field=models.CharField(choices=[('review', 'En revisión'), ('verified', 'Verificado')], default='review', max_length=255),
        ),
    ]
