# Generated by Django 4.1.5 on 2023-01-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_externalpayment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='large_description',
            field=models.TextField(help_text='Descripcion larga del producto del producto', max_length=5000, null=True),
        ),
    ]
