# Generated by Django 4.1.5 on 2023-01-20 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_products_large_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='categoria padre de esta categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
